Heading:
  default: "Bulb"
  max: 25
  description:
    en: "Text for the heading in the footer - you can use your site name for example - Max length 25 characters"
Heading_logo:
  default: 'logo'
  max: 25
  description:
    en: "Text for the heading in the footer - you can use your site name for example - Max length 25 characters"
Blurb:
  default: ""
  max: 180
  description:
    en: "Enter a short blurb about your community - Max length 180 characters"
Link_sections:
  type: list
  default: "Find Us, How to find us| Members, Bulb Members|About Bulb|Contact"
  description:
    en: 'Add link sections. The ideal number of sections is six. One item per line in this order:<br> Text, title<br><b>Text:</b> what appears on in the footer<br><b>Title:</b> the text that appears when the item is hovered.'
Links:
  type: list
  default: "Members, Sign in, https://account.bulb.co.uk/, blank, Sign   in|Members, Get a quote, https://join.bulb.co.uk/, blank, Get a   quote|Members, Refer a friend, https://bulb.co.uk/referral, blank,   |Members, Accessibility &amp;<br> priority   services,https://bulb.co.uk/accessibility|Find Us, Bulb<br>155   Bishopsgate<br> London EC2M 3TQ, #, blank, |About Bulb, About us,   https://bulb.co.uk/about, blank|About Bulb, Blog,   https://blog.bulb.co.uk/, blank|About Bulb, Carbon Tracker,   https://bulb.co.uk/carbon-tracker|About Bulb, Our Service,   https://bulb.co.uk/service, blank|About Bulb, Our tariff,   https://bulb.co.uk/tariff, blank|About Bulb, Our energy,   https://bulb.co.uk/energy, blank|About Bulb, Bulb Generators,   https://bulb.co.uk/generators, blank|About Bulb, Bulb for business,   https://bulb.co.uk/business, blank|About Bulb, Prepay,   https://bulb.co.uk/prepay, blank|About Bulb,Privacy policy,https://bulb.co.uk/privacy, blank|About Bulb,Cookie policy,   https://bulb.co.uk/cookies, blank|About Bulb, Modern   slavery<br>statement,https://bulb.co.uk/modern-slavery-statement,blank|About   Bulb,Termms &amp; conditions, https://bulb.co.uk/terms,blank|Contact, Help, https://bulb.co.uk/help, blank|Contact, Community, https://community.bulb.co.uk/, blank|Contact, Emergencies, https://help.bulb.co.uk/hc/en-us/articles/115001228911-What-to-do-in-case-of-emergency-, blank|Contact, Complaints, https://bulb.co.uk/complaints, blank|Contact, Press, https://bulb.co.uk/press, blank|Contact, Careers, https://bulb.co.uk/careers, blank"
  description:
    en: 'Add links to link sections. One item per line in this order:<br>Parent, text, URL, target, title<br>It is a good idea to keep the number of links under each section similar<br><b>Parent:</b> the name of the parent section which this link shows under. Use the `text` value from the list above<br><b>Text:</b> the text that shows for this link<br><b>URL:</b> the path this item links to. You can use relative paths as well.<br><b>Target:</b> Choose whether this item will open in a new tab or in the same tab. Use blank to open the link in a new tab, or use self to open it in the same tab.<br><b>Title:</b> the text that shows when the link is hovered.'
Small_links:
  type: list
  default: ""
  description:
    en: "You can add small links at the bottom of the footer like Terms of Service and Privacy. One item per line in this order:<br>Text, URL, target<br><b>Text:</b> The text that shows for the small link<br><b>URL:</b> The path of the link<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab"
Social_links:
  type: list
  default: "Facebook, Bulb on Facebook, https://facebook.com/bulb, blank,fab-facebook|Twitter, Bulb on Twitter, https://twitter.com/bulbenergy, blank,fab-twitter| Youtube, Bulb on Youtube, https://youtube.com/channel/UCdcnOLWqlPhTESp5SOMXqcA, blank,fab-youtube|Instagram, Bulb on Instagram, https://instagram.com/bulbstagram, blank, fab-instagram"
  description:
    en: "Enter the social links you'd like to add to the footer in this format:<br> provider, title, URL, target<br><b>Provider:</b> is the name of the provider like Facebook or Twitter<br><b>Title:</b> The text that shows when the link is hovered<br><b>URL:</b> The path you'd like the link to have<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab<br><b>Icon:</b> use a FontAwesome5 icon name (brand icons need a 'fab-' prefix)."
svg_icons:
  default: "fab-facebook|fab-twitter|fab-youtube|fab_instagram"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in the social links setting above. "
